package finalpro;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.JOptionPane;

/**
 *
 * @author Hanssen
 */
public class FinalProject extends javax.swing.JFrame{

    /** Creates new form FinalProject */
    public FinalProject() {
        initComponents();
    }
   
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        currchoice = new javax.swing.JComboBox<>();
        txt1 = new javax.swing.JTextField();
        conv = new javax.swing.JButton();
        idr = new javax.swing.JTextField();
        Idr = new javax.swing.JCheckBox();
        usd = new javax.swing.JTextField();
        Usd = new javax.swing.JCheckBox();
        cny = new javax.swing.JTextField();
        Cny = new javax.swing.JCheckBox();
        euro = new javax.swing.JTextField();
        Euro = new javax.swing.JCheckBox();
        jpy = new javax.swing.JTextField();
        Jpy = new javax.swing.JCheckBox();
        krw = new javax.swing.JTextField();
        Krw = new javax.swing.JCheckBox();
        bp = new javax.swing.JTextField();
        Bp = new javax.swing.JCheckBox();
        flags = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        currchoice.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        currchoice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Currency", "IDR", "USD", "CNY", "EURO", "JPY", "KRW", "BP", " ", " " }));
        currchoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currchoiceActionPerformed(evt);
            }
        });

        txt1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N

        conv.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        conv.setText("Convert");
        conv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convActionPerformed(evt);
            }
        });

        idr.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        idr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idrActionPerformed(evt);
            }
        });

        Idr.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        Idr.setText("IDR");
        Idr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdrActionPerformed(evt);
            }
        });

        usd.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N

        Usd.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        Usd.setText("USD");

        cny.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N

        Cny.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        Cny.setText("CNY");

        euro.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N

        Euro.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        Euro.setText("EURO");

        jpy.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N

        Jpy.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        Jpy.setText("JPY");

        krw.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N

        Krw.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        Krw.setText("KRW");

        bp.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N

        Bp.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        Bp.setText("BP");

        flags.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/regional-indicator-symbol-letters-id.png"))); // NOI18N
        flags.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(flags, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Bp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bp)
                            .addComponent(Euro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(euro)
                            .addComponent(idr)
                            .addComponent(Idr, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(currchoice, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(136, 136, 136)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(usd)
                                    .addComponent(Usd, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                                    .addComponent(jpy)
                                    .addComponent(Jpy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(127, 127, 127)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(krw)
                                    .addComponent(Cny, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                                    .addComponent(Krw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cny)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(123, 123, 123)
                                .addComponent(conv, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(flags, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currchoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conv))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Idr)
                    .addComponent(Usd)
                    .addComponent(Cny))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cny, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Euro)
                    .addComponent(Jpy)
                    .addComponent(Krw))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(euro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(krw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(Bp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idrActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_idrActionPerformed

    private void IdrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdrActionPerformed

    private void currchoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currchoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currchoiceActionPerformed

    private void convActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convActionPerformed
        // TODO add your handling code here:
        double input = Double.parseDouble(txt1.getText());
        
        if (currchoice.getSelectedItem().equals("Choose currency")) {
            JOptionPane.showMessageDialog(this, "Choose currency~");
            
        } else {
            
        if(Idr.isSelected()){

        if(currchoice.getSelectedItem().equals("IDR")){
            String toIdr = String.format("IDR %.2f", input * 1);
            idr.setText(toIdr);
        }
            } else {
            
                idr.setText("");
            }
        if(Usd.isSelected()){

       /* if(currchoice.getSelectedItem().equals("USD")){
            String toIdr = String.format("USD %.2f", input * 12000);
            idr.setText(toIdr);
        }
            } else {
            
                idr.setText("");
            }
        }*/
    }//GEN-LAST:event_convActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinalProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinalProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinalProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinalProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinalProject().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Bp;
    private javax.swing.JCheckBox Cny;
    private javax.swing.JCheckBox Euro;
    private javax.swing.JCheckBox Idr;
    private javax.swing.JCheckBox Jpy;
    private javax.swing.JCheckBox Krw;
    private javax.swing.JCheckBox Usd;
    private javax.swing.JTextField bp;
    private javax.swing.JTextField cny;
    private javax.swing.JButton conv;
    private javax.swing.JComboBox<String> currchoice;
    private javax.swing.JTextField euro;
    private javax.swing.JLabel flags;
    private javax.swing.JTextField idr;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jpy;
    private javax.swing.JTextField krw;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField usd;
    // End of variables declaration//GEN-END:variables

    
}
